import type { Metadata } from "next";

import NavBar from "@/components/navbar/navbar";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-dvh">
      <NavBar />
      <Header />
      <main className="fixed top-15 bottom-18 left-0 right-0 flex overflow-auto">
        {children}
      </main>
    </div>
  );
}
